rm ./lambdabot-core/dist --recursive --force
rm ./lambdabot-trusted --recursive --force
rm ./lambdabot-hangman-plugins --recursive --force
rm ./lambdabot-points-plugins --recursive --force
rm ./lambdabot-suggest-plugins --recursive --force
rm ./lambdabot-social-plugins --recursive --force
rm ./lambdabot-reference-plugins --recursive --force
rm ./lambdabot-novelty-plugins --recursive --force
rm ./lambdabot-misc-plugins --recursive --force
rm ./lambdabot-irc-plugins --recursive --force
rm ./lambdabot-twitch-plugins --recursive --force
rm ./lambdabot-haskell-plugins --recursive --force
rm ./lambdabot --recursive --force
