rm ./lambdabot-core/dist --recursive --force
rm ./lambdabot-trusted/dist --recursive --force
rm ./lambdabot-hangman-plugins/dist --recursive --force
rm ./lambdabot-points-plugins/dist --recursive --force
rm ./lambdabot-suggest-plugins/dist --recursive --force
rm ./lambdabot-social-plugins/dist --recursive --force
rm ./lambdabot-reference-plugins/dist --recursive --force
rm ./lambdabot-novelty-plugins/dist --recursive --force
rm ./lambdabot-misc-plugins/dist --recursive --force
rm ./lambdabot-irc-plugins/dist --recursive --force
rm ./lambdabot-twitch-plugins/dist --recursive --force
rm ./lambdabot-haskell-plugins/dist --recursive --force
rm ./lambdabot/dist --recursive --force
